# Generated by Django 2.1.3 on 2019-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Engsub', models.TextField(max_length=20)),
                ('Vietsub', models.TextField(max_length=200)),
            ],
        ),
    ]
